#!/bin/bash
# Samples a running Rewinder install and writes NEW_PERFORMANCE_REPORT.md
# with the numbers for THIS machine (any RAM size: 8/16/32/64 GB...).
#
# Usage:
#   1. Launch Rewinder and turn the replay buffer ON.
#   2. bash scripts/measure_performance.sh
#
# Tunables: SAMPLES=12 INTERVAL=5 OUT=NEW_PERFORMANCE_REPORT.md
set -u

cd "$(dirname "$0")/.."

SAMPLES="${SAMPLES:-12}"
INTERVAL="${INTERVAL:-5}"
OUT="${OUT:-NEW_PERFORMANCE_REPORT.md}"

app_pid()    { pgrep -f "MacOS/Rewinder$" 2>/dev/null | head -1; }
helper_pid() { pgrep -f "rewinder-sck-capture" 2>/dev/null | head -1; }
ffmpeg_pid() { pgrep -f "Resources/bin/ffmpeg" 2>/dev/null | head -1; }

APP_PID="$(app_pid)"
HELPER_PID="$(helper_pid)"
FFMPEG_PID="$(ffmpeg_pid)"

if [ -z "$APP_PID" ]; then
  echo "error: Rewinder is not running." >&2
  echo "Launch Rewinder.app, turn the replay buffer ON, then re-run this script." >&2
  exit 1
fi
if [ -z "$HELPER_PID" ] || [ -z "$FFMPEG_PID" ]; then
  echo "error: Rewinder is running but the replay buffer is OFF (capture helpers not found)." >&2
  echo "Turn the replay buffer ON (the big ring), wait ~10 seconds, then re-run." >&2
  exit 1
fi

MODEL="$(sysctl -n hw.model 2>/dev/null || echo unknown)"
CHIP="$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo unknown)"
RAM_GB="$(( $(sysctl -n hw.memsize) / 1073741824 ))"
CORES_ALL="$(sysctl -n hw.ncpu 2>/dev/null || echo '?')"
CORES_PERF="$(sysctl -n hw.perflevel0.physicalcpu 2>/dev/null || echo '?')"
CORES_EFF="$(sysctl -n hw.perflevel1.physicalcpu 2>/dev/null || echo '?')"
MACOS_VER="$(sw_vers -productVersion 2>/dev/null || echo unknown)"
MACOS_BUILD="$(sw_vers -buildVersion 2>/dev/null || echo unknown)"
DARWIN="$(uname -r)"
RUN_DATE="$(date '+%Y-%m-%d %H:%M %Z')"

phys_footprint() {
  vmmap --summary "$1" 2>/dev/null | awk '/^Physical footprint:/{print $3; exit}'
}
phys_peak() {
  vmmap --summary "$1" 2>/dev/null | awk '/^Physical footprint \(peak\):/{print $4; exit}'
}

TMPDIR_DATA="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_DATA"' EXIT

echo "Sampling $SAMPLES times every ${INTERVAL}s (~$(( SAMPLES * INTERVAL ))s total). Keep using your Mac normally..."

i=0
while [ "$i" -lt "$SAMPLES" ]; do
  APP_PID="$(app_pid)"; HELPER_PID="$(helper_pid)"; FFMPEG_PID="$(ffmpeg_pid)"
  for role in app helper ffmpeg; do
    case "$role" in
      app) pid="$APP_PID" ;;
      helper) pid="$HELPER_PID" ;;
      ffmpeg) pid="$FFMPEG_PID" ;;
    esac
    if [ -n "$pid" ]; then
      ps -o rss=,pcpu= -p "$pid" 2>/dev/null | awk -v r="$role" '{print r, $1, $2}' >> "$TMPDIR_DATA/samples"
    fi
  done
  i=$(( i + 1 ))
  [ "$i" -lt "$SAMPLES" ] && sleep "$INTERVAL"
done

APP_PHYS="$(phys_footprint "$APP_PID")";       APP_PHYS_PEAK="$(phys_peak "$APP_PID")"
HELPER_PHYS="$(phys_footprint "$HELPER_PID")"; HELPER_PHYS_PEAK="$(phys_peak "$HELPER_PID")"
FFMPEG_PHYS="$(phys_footprint "$FFMPEG_PID")"; FFMPEG_PHYS_PEAK="$(phys_peak "$FFMPEG_PID")"

stats_for() {
  awk -v r="$1" '
    $1 == r { n++; rss += $2; cpu += $3; if ($2 > rssmax) rssmax = $2; if ($3 > cpumax) cpumax = $3 }
    END {
      if (n == 0) { print "n/a n/a n/a n/a"; exit }
      printf "%.0f %.0f %.1f %.1f\n", rss / n / 1024, rssmax / 1024, cpu / n, cpumax
    }' "$TMPDIR_DATA/samples"
}

read -r APP_RSS_AVG APP_RSS_MAX APP_CPU_AVG APP_CPU_MAX <<EOF_STATS
$(stats_for app)
EOF_STATS
read -r HELPER_RSS_AVG HELPER_RSS_MAX HELPER_CPU_AVG HELPER_CPU_MAX <<EOF_STATS
$(stats_for helper)
EOF_STATS
read -r FFMPEG_RSS_AVG FFMPEG_RSS_MAX FFMPEG_CPU_AVG FFMPEG_CPU_MAX <<EOF_STATS
$(stats_for ffmpeg)
EOF_STATS

LIVE_DIR="$(lsof -p "$FFMPEG_PID" 2>/dev/null | awk '/\.rewinder-live/{print $NF; exit}')"
LIVE_DIR="${LIVE_DIR%/*}"
SEG_COUNT="n/a"; BUF_MB="n/a"; WRITE_RATE="n/a"; RETAINED_S="n/a"
if [ -n "$LIVE_DIR" ] && [ -d "$LIVE_DIR" ]; then
  SEG_COUNT="$(ls "$LIVE_DIR" 2>/dev/null | grep -c '\.mp4$')"
  BUF_KB="$(du -sk "$LIVE_DIR" 2>/dev/null | cut -f1)"
  BUF_MB="$(awk -v k="$BUF_KB" 'BEGIN{printf "%.0f MB", k/1024}')"
  SECS="$(awk -v n="$SEG_COUNT" 'BEGIN{printf "%.0f", n*0.5}')"
  RETAINED_S="~${SECS}s"
  if [ "$SECS" != "0" ]; then
    WRITE_RATE="$(awk -v k="$BUF_KB" -v s="$SECS" 'BEGIN{printf "%.2f MB/s", k/1024/s}')"
  fi
fi

POWER_SOURCE="$(pmset -g batt 2>/dev/null | head -1 | sed "s/Now drawing from //;s/'//g")"
THERMAL="$(pmset -g therm 2>/dev/null | awk '/CPU_Speed_Limit/{print "CPU speed limit " $3 "%"}')"
[ -z "$THERMAL" ] && THERMAL="no thermal throttling data"

cat > "$OUT" <<EOF_REPORT
# Rewinder — Performance Report (your machine)

Generated by \`scripts/measure_performance.sh\` — compare against the reference numbers in \`PERFORMANCE_REPORT.md\`.

**Date:** $RUN_DATE
**Machine:** $MODEL · $CHIP · **${RAM_GB} GB RAM** · ${CORES_ALL} cores (${CORES_PERF}P + ${CORES_EFF}E)
**macOS:** $MACOS_VER ($MACOS_BUILD, darwin $DARWIN)
**Power:** $POWER_SOURCE · $THERMAL
**Method:** $SAMPLES samples, one every ${INTERVAL}s, while the replay buffer was armed.

## Per-process results

\`ps\` RSS overcounts shared frameworks and IOSurface/GPU memory; \`vmmap\` Physical footprint is what Activity Monitor calls "Memory" and is the honest number.

| Process | Role | RSS avg | RSS max | vmmap phys ("Memory") | phys peak | CPU avg (1 core) | CPU max |
|---|---|---:|---:|---:|---:|---:|---:|
| \`Rewinder\` (app) | SwiftUI UI + Rust engine (FFI, in-process) | ${APP_RSS_AVG} MB | ${APP_RSS_MAX} MB | ${APP_PHYS:-n/a} | ${APP_PHYS_PEAK:-n/a} | ${APP_CPU_AVG}% | ${APP_CPU_MAX}% |
| \`rewinder-sck-capture\` | ScreenCaptureKit helper (video + audio) | ${HELPER_RSS_AVG} MB | ${HELPER_RSS_MAX} MB | ${HELPER_PHYS:-n/a} | ${HELPER_PHYS_PEAK:-n/a} | ${HELPER_CPU_AVG}% | ${HELPER_CPU_MAX}% |
| \`ffmpeg\` | HW H.264 encode + audio DSP + segment mux | ${FFMPEG_RSS_AVG} MB | ${FFMPEG_RSS_MAX} MB | ${FFMPEG_PHYS:-n/a} | ${FFMPEG_PHYS_PEAK:-n/a} | ${FFMPEG_CPU_AVG}% | ${FFMPEG_CPU_MAX}% |

## Rolling buffer (disk)

| Metric | Value |
|---|---:|
| Live segments on disk | $SEG_COUNT |
| Retained footage (0.5s segments) | $RETAINED_S |
| Buffer size on disk | $BUF_MB |
| Estimated write rate | $WRITE_RATE |

## Caveats

- CPU percentages are of one core (like Activity Monitor); the helper's cost scales with how busy your screen content is.
- The SCK helper's footprint varies with screen content — don't mistake a startup transient for steady state.
- Numbers depend on your quality preset, replay window, mic/noise-removal settings, and what else the machine was doing during sampling.
EOF_REPORT

echo "Done: $OUT"
